spring.application.name=auth-service

server.port=8081

# ==== DATABASE ====
spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5433}/${AUTH_DB_NAME:auth_db}
spring.datasource.username=${AUTH_DB_USER:auth_user}
spring.datasource.password=${AUTH_DB_PASSWORD:auth_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ==== JWT ====
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# ==== KAFKA ====
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

kafka.topic.user-registered=user-registered-topic

# ==== LOGGING ====
logging.level.com.sorokaandriy.auth_service=INFO

# ==== CORS ====
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
