spring.application.name=order-service

server.port=8083

# ==== DATABASE ====
spring.datasource.url=jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5435}/${ORDER_DB_NAME:order_db}
spring.datasource.username=${ORDER_DB_USER:order_user}
spring.datasource.password=${ORDER_DB_PASSWORD:order_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ==== JWT (validation only, token is issued by auth-service) ====
jwt.secret=${JWT_SECRET}

# ==== KAFKA ====
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

kafka.topic.order-created=order-created-topic

# ==== EXTERNAL SERVICES ====
app.product-service-url=${PRODUCT_SERVICE_URL:http://localhost:8082}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# ==== LOGGING ====
logging.level.com.sorokaandriy.order_service=INFO
